services:
  frontend:
    image: todo-frontend-dev
    build: 
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    environment:
      - PORT=6666
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-frontend-dev-with-nginx
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8006:80
    container_name: nginx