services:
  frontend:
    container_name: todo-frontend
    image: todo-frontend
    tty: true
    build:
      context: ./todo-frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://nginx
    volumes:
      - static_files:/usr/src/app/build
  nginx:
    container_name: todo-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_files:/usr/src/app/build
    ports:
      - 20080:80
  mongo:
    container_name: todo-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis:
    container_name: todo-redis
    image: redis
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data
  backend:
    container_name: todo-backend
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: ./Dockerfile
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
      - PORT=9999

volumes:
  mongo_data: null
  redis_data: null
  static_files: null
